name: Clippy Checks
on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
jobs:
  run-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Initialize git submodules"
        run: |
          git submodule update --init --recursive
      - name: "Install Rust toolchain"
        run: |
          (echo "rustup toolchain install "; cat rust-toolchain; printf -- "-x86_64-unknown-linux-gnu;"; echo "rustup component add clippy rust-src --toolchain "; cat rust-toolchain; printf -- "-x86_64-unknown-linux-gnu;") | tr -d "\r" | tr -d "\n" > cmd.txt
          bash cmd.txt;
      - name: "Run Clippy"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          cargo clippy
          -q -Z build-std=core,alloc 
          -Z build-std-features=compiler-builtins-mem 
          --target cfg/x86_64-theseus.json 
          --workspace --all-features -- 
          -A clippy::all 

          # Complexity

          -D clippy::bind-instead-of-map
          -D clippy::bool-comparison
          # -D clippy::borrowed-box
          # -D clippy::bytes-count-to-len
          # -D clippy::char-lit-as-u8
          # -D clippy::clone-on-copy
          # -D clippy::crosspointer-transmute
          # -D clippy::deprecated-cfg-attr
          # -D clippy::deref-addrof
          # -D clippy::derivable-impls
          # -D clippy::diverging-sub-expression
          # -D clippy::double-comparisons
          # -D clippy::double-parens
          # -D clippy::duration-subsec
          # -D clippy::explicit-counter-loop
          # -D clippy::explicit-write
          # -D clippy::extra-unused-lifetimes
          # -D clippy::filter-map-identity
          -D clippy::filter-next
          # -D clippy::flat-map-identity
          # -D clippy::get-last-with-len
          # -D clippy::identity-op
          # -D clippy::inspect-for-each
          # -D clippy::int-plus-one
          # -D clippy::iter-count
          # -D clippy::manual-filter-map
          # -D clippy::manual-find-map
          # -D clippy::manual-flatten
          # -D clippy::manual-split-once
          # -D clippy::manual-strip
          # -D clippy::manual-swap
          -D clippy::manual-unwrap-or
          # -D clippy::map-flatten
          # -D clippy::map-identity
          # -D clippy::match-as-ref
          # -D clippy::match-single-binding
          # -D clippy::needless-arbitrary-self-type
          # -D clippy::needless-bool
          # -D clippy::needless-borrowed-reference
          # -D clippy::needless-lifetimes
          # -D clippy::needless-match
          # -D clippy::needless-option-as-deref
          # -D clippy::needless-option-take
          # -D clippy::needless-question-mark
          # -D clippy::needless-splitn
          # -D clippy::needless-update
          # -D clippy::neg-cmp-op-on-partial-ord
          # -D clippy::no-effect
          -D clippy::nonminimal-bool
          # -D clippy::option-as-ref-deref
          # -D clippy::option-filter-map
          # -D clippy::option-map-unit-fn
          # -D clippy::or-then-unwrap
          # -D clippy::overflow-check-conditional
          # -D clippy::partialeq-ne-impl
          # -D clippy::precedence
          # -D clippy::ptr-offset-with-cast
          # -D clippy::range-zip-with-len
          # -D clippy::redundant-closure-call
          # -D clippy::redundant-slicing
          # -D clippy::repeat-once
          # -D clippy::result-map-unit-fn
          # -D clippy::search-is-some
          # -D clippy::short-circuit-statement
          # -D clippy::single-element-loop
          # -D clippy::skip-while-next
          # -D clippy::string-from-utf8-as-bytes
          # -D clippy::strlen-on-c-strings
          # -D clippy::temporary-assignment
          # -D clippy::too-many-arguments
          # -D clippy::transmute-bytes-to-str
          # -D clippy::transmute-float-to-int
          # -D clippy::transmute-int-to-bool
          # -D clippy::transmute-int-to-char
          # -D clippy::transmute-int-to-float
          # -D clippy::transmute-num-to-bytes
          # -D clippy::transmute-ptr-to-ref
          # -D clippy::transmutes-expressible-as-ptr-casts
          # -D clippy::type-complexity
          # -D clippy::unit-arg
          # -D clippy::unnecessary-cast
          # -D clippy::unnecessary-filter-map
          # -D clippy::unnecessary-find-map
          # -D clippy::unnecessary-operation
          # -D clippy::unnecessary-sort-by
          # -D clippy::unnecessary-unwrap
          # -D clippy::unneeded-wildcard-pattern
          -D clippy::useless-asref
          # -D clippy::useless-conversion
          # -D clippy::useless-format
          # -D clippy::vec-box
          -D clippy::while-let-loop
          # -D clippy::wildcard-in-or-patterns
          # -D clippy::zero-divided-by-zero
          # -D clippy::zero-prefixed-literal

          # Correctness

          -D clippy::absurd-extreme-comparisons
          # -D clippy::almost-swapped
          # -D clippy::approx-constant
          # -D clippy::async-yields-async
          # -D clippy::bad-bit-mask
          # -D clippy::cast-ref-to-mut
          # -D clippy::cast-slice-different-sizes
          # -D clippy::clone-double-ref
          # -D clippy::cmp-nan
          # -D clippy::deprecated-semver
          -D clippy::derive-hash-xor-eq
          -D clippy::derive-ord-xor-partial-ord
          # -D clippy::drop-copy
          # -D clippy::drop-ref
          -D clippy::enum-clike-unportable-variant
          # -D clippy::eq-op
          # -D clippy::erasing-op
          # -D clippy::fn-address-comparisons
          # -D clippy::forget-copy
          # -D clippy::forget-ref
          # -D clippy::if-let-mutex
          # -D clippy::if-same-then-else
          # -D clippy::ifs-same-cond
          # -D clippy::ineffective-bit-mask
          # -D clippy::infinite-iter
          # -D clippy::inherent-to-string-shadow-display
          # -D clippy::inline-fn-without-body
          # -D clippy::invalid-null-ptr-usage
          # -D clippy::invalid-regex
          # -D clippy::invisible-characters
          # -D clippy::iter-next-loop
          # -D clippy::iterator-step-by-zero
          # -D clippy::let-underscore-lock
          # -D clippy::logic-bug
          # -D clippy::match-str-case-mismatch
          # -D clippy::mem-replace-with-uninit
          # -D clippy::min-max
          # -D clippy::mismatched-target-os
          # -D clippy::mistyped-literal-suffixes
          # -D clippy::modulo-one
          # -D clippy::mut-from-ref
          # -D clippy::never-loop
          # -D clippy::non-octal-unix-permissions
          # -D clippy::nonsensical-open-options
          # -D clippy::not-unsafe-ptr-arg-deref
          # -D clippy::option-env-unwrap
          # -D clippy::out-of-bounds-indexing
          # -D clippy::panicking-unwrap
          # -D clippy::possible-missing-comma
          # -D clippy::recursive-format-impl
          # -D clippy::reversed-empty-ranges
          # -D clippy::self-assignment
          # -D clippy::serde-api-misuse
          # -D clippy::size-of-in-element-count
          # -D clippy::suspicious-splitn
          # -D clippy::transmuting-null
          # -D clippy::undropped-manually-drops
          # -D clippy::uninit-assumed-init
          # -D clippy::uninit-vec
          # -D clippy::unit-cmp
          # -D clippy::unit-hash
          # -D clippy::unit-return-expecting-ord
          # -D clippy::unsound-collection-transmute
          # -D clippy::unused-io-amount
          # -D clippy::useless-attribute
          # -D clippy::vec-resize-to-zero
          # -D clippy::vtable-address-comparisons
          # -D clippy::while-immutable-condition
          # -D clippy::wrong-transmute
          # -D clippy::zst-offset

          # Style

          # -D clippy::assertions-on-constants
          # -D clippy::assign-op-pattern
          # -D clippy::blacklisted-name
          # -D clippy::blocks-in-if-conditions
          # -D clippy::bool-assert-comparison
          # -D clippy::borrow-interior-mutable-const
          # -D clippy::builtin-type-shadow
          # -D clippy::bytes-nth
          # -D clippy::chars-last-cmp
          # -D clippy::chars-next-cmp
          # -D clippy::cmp-null
          # -D clippy::collapsible-else-if
          # -D clippy::collapsible-if
          # -D clippy::collapsible-match
          # -D clippy::comparison-chain
          # -D clippy::comparison-to-empty
          # -D clippy::declare-interior-mutable-const
          # -D clippy::disallowed-methods
          # -D clippy::disallowed-types
          # -D clippy::double-must-use
          # -D clippy::double-neg
          # -D clippy::duplicate-underscore-argument
          # -D clippy::enum-variant-names
          # -D clippy::err-expect
          # -D clippy::excessive-precision
          # -D clippy::field-reassign-with-default
          # -D clippy::fn-to-numeric-cast
          # -D clippy::fn-to-numeric-cast-with-truncation
          # -D clippy::for-kv-map
          # -D clippy::from-over-into
          # -D clippy::from-str-radix-10
          # -D clippy::inconsistent-digit-grouping
          # -D clippy::infallible-destructuring-match
          # -D clippy::inherent-to-string
          # -D clippy::init-numbered-fields
          # -D clippy::into-iter-on-ref
          # -D clippy::is-digit-ascii-radix
          # -D clippy::iter-cloned-collect
          # -D clippy::iter-next-slice
          # -D clippy::iter-nth-zero
          # -D clippy::iter-skip-next
          # -D clippy::just-underscores-and-digits
          # -D clippy::len-without-is-empty
          # -D clippy::len-zero
          # -D clippy::let-and-return
          # -D clippy::let-unit-value
          # -D clippy::main-recursion
          # -D clippy::manual-async-fn
          # -D clippy::manual-bits
          # -D clippy::manual-map
          # -D clippy::manual-non-exhaustive
          # -D clippy::manual-range-contains
          # -D clippy::manual-saturating-arithmetic
          # -D clippy::map-clone
          # -D clippy::map-collect-result-unit
          # -D clippy::match-like-matches-macro
          # -D clippy::match-overlapping-arm
          # -D clippy::match-ref-pats
          # -D clippy::match-result-ok
          # -D clippy::mem-replace-option-with-none
          # -D clippy::mem-replace-with-default
          # -D clippy::missing-safety-doc
          # -D clippy::mixed-case-hex-literals
          # -D clippy::module-inception
          # -D clippy::must-use-unit
          # -D clippy::mut-mutex-lock
          # -D clippy::needless-borrow
          # -D clippy::needless-doctest-main
          # -D clippy::needless-late-init
          # -D clippy::needless-range-loop
          # -D clippy::needless-return
          # -D clippy::neg-multiply
          # -D clippy::new-ret-no-self
          # -D clippy::new-without-default
          # -D clippy::ok-expect
          # -D clippy::op-ref
          # -D clippy::option-map-or-none
          # -D clippy::print-literal
          # -D clippy::print-with-newline
          # -D clippy::println-empty-string
          # -D clippy::ptr-arg
          # -D clippy::ptr-eq
          # -D clippy::question-mark
          # -D clippy::redundant-closure
          # -D clippy::redundant-field-names
          # -D clippy::redundant-pattern
          # -D clippy::redundant-pattern-matching
          # -D clippy::redundant-static-lifetimes
          # -D clippy::result-map-or-into-option
          # -D clippy::result-unit-err
          # -D clippy::same-item-push
          # -D clippy::self-named-constructors
          # -D clippy::should-implement-trait
          # -D clippy::single-char-add-str
          # -D clippy::single-component-path-imports
          # -D clippy::single-match
          # -D clippy::string-extend-chars
          # -D clippy::tabs-in-doc-comments
          # -D clippy::to-digit-is-some
          # -D clippy::toplevel-ref-arg
          # -D clippy::trim-split-whitespace
          # -D clippy::unnecessary-fold
          # -D clippy::unnecessary-lazy-evaluations
          # -D clippy::unnecessary-mut-passed
          # -D clippy::unnecessary-owned-empty-strings
          # -D clippy::unsafe-removed-from-name
          # -D clippy::unused-unit
          # -D clippy::unusual-byte-groupings
          # -D clippy::unwrap-or-else-default
          # -D clippy::upper-case-acronyms
          # -D clippy::while-let-on-iterator
          # -D clippy::write-literal
          # -D clippy::write-with-newline
          # -D clippy::writeln-empty-string
          # -D clippy::wrong-self-convention ¶
          # -D clippy::zero-ptr

          # Nursery

          # -D clippy::empty-line-after-outer-attr
          # -D clippy::fallible-impl-from
          # -D clippy::mutex-integer
          # -D clippy::needless-borrow
          # -D clippy::panicking-unwrap
          # -D clippy::range-plus-one
          # -D clippy::unnecessary-unwrap

          # Perf

          # -D clippy::box-collection
          # -D clippy::boxed-local
          -D clippy::cmp-owned
          -D clippy::expect-fun-call
          # -D clippy::extend-with-drain
          # -D clippy::format-in-format-args
          # -D clippy::format-push-string
          # -D clippy::iter-nth
          # -D clippy::iter-overeager-cloned
          # -D clippy::large-const-arrays
          # -D clippy::large-enum-variant
          # -D clippy::manual-memcpy
          # -D clippy::manual-str-repeat
          # -D clippy::map-entry
          # -D clippy::missing-spin-loop
          # -D clippy::needless-collect
          -D clippy::or-fun-call
          # -D clippy::redundant-allocation
          -D clippy::redundant-clone
          -D clippy::single-char-pattern
          # -D clippy::slow-vector-initialization
          -D clippy::to-string-in-format-args
          # -D clippy::unnecessary-to-owned
          # -D clippy::useless-vec
          -D clippy::vec-init-then-push

          # Suspicious

          # -D clippy::await-holding-invalid-type
          # -D clippy::await-holding-lock
          # -D clippy::await-holding-refcell-ref
          # -D clippy::blanket-clippy-restriction-lints
          # -D clippy::cast-abs-to-unsigned
          # -D clippy::cast-enum-constructor
          # -D clippy::cast-enum-truncation
          # -D clippy::crate-in-macro-def
          # -D clippy::drop-non-drop
          # -D clippy::empty-loop
          # -D clippy::eval-order-dependence
          # -D clippy::float-equality-without-abs
          # -D clippy::for-loops-over-fallibles
          # -D clippy::forget-non-drop
          # -D clippy::misrefactored-assign-op
          # -D clippy::mut-range-bound
          # -D clippy::mutable-key-type
          # -D clippy::octal-escapes
          # -D clippy::print-in-format-impl
          # -D clippy::suspicious-arithmetic-impl
          # -D clippy::suspicious-assignment-formatting
          # -D clippy::suspicious-else-formatting
          # -D clippy::suspicious-map
          # -D clippy::suspicious-op-assign-impl
          # -D clippy::suspicious-unary-op-formatting
